# Generated by Django 3.1.3 on 2020-11-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=45)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
